image:
  file: .gitpod.dockerfile
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers

    - ms-python.python

    - ms-toolsai.vscode-jupyter-slideshow
    - ms-python.debugpyscode-jupyter-slideshow
hon.debugpyscode-jupyter-slideshow
deshow
hon.debugpyscode-jupyter-slideshow

